### ISSUE TITLE
Community Meeting Meta Issue [BREAKING CHANGES]

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#354]
Let's discuss the breaking changes coming on Dynaconf 3.0.0 https://doodle.com/poll/ke2g4kc6mzwgtavh

There are some issues still opened for 3.0 https://github.com/rochacbruno/dynaconf/milestone/9

The highlights to be discussed are:

- **Global `settings` object is going to be deprecated**
    Users must create their own instance of dynaconf 
    **Deprecate**    
    ```py
    from dynaconf import settings
    ```
    **New recommended way**
    ```py
     # yourprogram/config.py
     settings = Dynaconf(**options)`
    ```
    **reason**
    Most users are confused about importing direct from dynaconf a singleton config object and when
    customizations via `**options` are needed they have to change the whole codebase.

- **No more default file paths** 
   Right now Dynaconf loads all files named `settings.*` 
   idea is making it explicit only via option 
   `settings_files=[list of paths or globs]`
   e.g:
   ```py
   from dynaconf import Dynaconf
   settings = Dynaconf(settings_files=["main.toml", "other.toml", "path/*.toml"])
   ```
   **reason**
   Debugging file loading is hard, permissions and other I/O problems may happen
   idea is to make explicit and raise earlier for errors.

- Envless mode will be default

  Now dynaconf has an `envless_mode`, which means it can load
  all variables direct from the main level of a file.

  ```toml
  server = 'bar.com'
  port = 5050
  ```

  This will be the default and if needed users will provide the
  list of environments.

  ```py
  settings = Dynaconf(envs=["development", "production"])
  ```

  then

  ```toml
  [default]
  server = 'bar.com'
  port = 5050
  [development]
  server = 'dev.com'
  [production]
  server = 'prod.com'
  port = 80
  ```

- **Allow parser to be changed or disabled** 
   Right now `toml` is the only parser for every variable, 
   idea is to make it configurable (and allow users to opt-out)
   **reason**
   Some users reported that wanted raw values instead of parsed 
   by toml.
   
- **dotenv will be disabled by default** 
  No more loading of `.env` unless users explicitly enables it.
  **reason**
  In some environments dotenv is already loaded by the shell tool
  
- Validators will fire by default if passed to the settings object
  No need to explicity call **settings.validators.validate()**
  if `Dynaconf(validators=[...])` is passed it will be called
  right after the initialization.

- Remove logging completely
  **reason**
  It is easier to debug using pdb/ipdb, logging right now is 
  useless.

- Allow Pydantic BaseModels as validators

**Comment by And2Devel** [comment]
Hi Bruno

Let me comment first bullet: right now it is very simple: you simply adding 'import dynaconf' in each module where you want to use settings, and then, referring to parameters through settings.SOMETHING. With this change, will I have to declare settings object.. in every module? every function?

It seems difficult, especially because my app changing values of parameters sometimes - then an object declared somewhere will miss these changes.. Or am I wrong?

**Comment by rochacbruno** [comment]
@And2Devel hi, the idea is that somewhere in your project you create your own main settings object.

**program/config.py**
```py
from dynaconf import Dynaconf
settings = Dynaconf(**options)
```

then in other parts of your program you just import `from program.config import settings`

**Comment by And2Devel** [comment]
OK, I see.
What about changing value of a parameter?
Will I have to use "global" in every function, like below?
```
def example_function():
    global settings
    settings.SOMETHING = 'value'`
```

**Comment by rochacbruno** [comment]
@And2Devel no, you don't need to use `global` the only change is that instead of importing the settings from `dynaconf` directly you will start importing from `yourprogram.config` the usage remains the same.

**Comment by RonnyPfannschmidt** [comment]
in insights-qe we pretty much completely try to avoid the global variable and try to set up multiple own instances per "application object"  - we collect settings files from a number of python package data folders and want to grow the ability to easyly create views to a specifiv settings instance with overrides layered on top

**Comment by rochacbruno** [comment]
Dynaconf COmmunity meeting is recorded here: Available for 60 days: https://www.twitch.tv/videos/647819477

**Comment by rochacbruno** [comment]
the version 3.0.0 is implementing the main changes:

- [ ] envless by default
- [ ] no more global settings object (you need to instantiate one yourself)
- [ ] no more loading of .env files unless user specifies load_dotenv=True 
- [ ] first level variables can now be accessed using lowercase settings.server.hostname for exemple (before upper was mandatory settings.SERVER.hostname) #272 
- [ ] settings path or glob should be provided by user, dynaconf will not try to load settings.* by default #310 
- [ ] Logging to be completelly removed #352 


"Explicit is better than implicit"

**Comment by rochacbruno** [comment]
All the changes discussed on this issue has been implemented!

Details on https://github.com/rochacbruno/dynaconf/blob/master/3.x-release-notes.md

Pre release `rc2` is coming tomorrow and I can use some help for testing.
